# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Checkout mainline commit on local repo and run tests.
name: Adreno Package Generation

on:
  schedule:
    # 2:30 AM IST
    - cron: "1 20 * * *"
  workflow_dispatch:

concurrency:
  group: mlcpkg
  cancel-in-progress: true

jobs:
  BuildPackageLinux:
    if: github.repository == 'gpgpu/mlc-llm'
    runs-on: mlc-linux-ci
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: 'recursive'
            fetch-depth: 0
      - name: Build MLC CPU Host Wheel
        shell: bash -l {0}
        run: |
           set -e
           gh release delete nightly --cleanup-tag --yes --repo git@github.qualcomm.com:gpgpu/mlc-llm.git || true
           bash ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cpu \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               conda run -n py38 ./ci/task/build_adreno_lib.sh
           bash ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cpu \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               -e WHEEL_EXT_NAME "_adreno_cpu" \
               conda run -n py38 ./ci/task/build_wheel.sh
           mkdir -p nightly
           cp wheels/*.whl nightly/
           bash ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cpu \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               conda run -n py38 ./ci/task/build_clean.sh
      - name: Build MLC CUDA Host Wheel
        shell: bash -l {0}
        run: |
           set -e
           bash ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cuda-12.1 \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               conda run -n py38 ./ci/task/build_adreno_lib.sh
           bash ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cuda-12.1 \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               -e WHEEL_EXT_NAME "_adreno_cuda" \
               conda run -n py38 ./ci/task/build_wheel.sh
           mkdir -p nightly
           cp wheels/*.whl nightly/
           bash ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cuda-12.1 \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               conda run -n py38 ./ci/task/build_clean.sh
      - name: Build TVM CPU Host Wheel
        shell: bash -l {0}
        run: |
           set -e
           cd 3rdparty/tvm
           bash ../../ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cpu \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               conda run -n py38 ./ci/adreno/build_lib.sh
           bash ../../ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cpu \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               -e WHEEL_EXT_NAME "_adreno_mlc_cpu" \
               conda run -n py38 ./ci/adreno/build_wheel.sh
           mkdir -p ../../nightly
           cp wheels/*.whl ../../nightly/
           bash ../../ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cpu \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               conda run -n py38 ./ci/adreno/build_clean.sh
           cd -
      - name: Build TVM CUDA Host Wheel
        shell: bash -l {0}
        run: |
           set -e
           cd 3rdparty/tvm
           bash ../../ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cuda-12.1 \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               conda run -n py38 ./ci/adreno/build_lib.sh
           bash ../../ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cuda-12.1 \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               -e WHEEL_EXT_NAME "_adreno_mlc_cuda" \
               conda run -n py38 ./ci/adreno/build_wheel.sh
           mkdir -p ../../nightly
           cp wheels/*.whl ../../nightly/
           bash ../../ci/bash.sh mlcaidev/package-cu121 \
               -e GPU cuda-12.1 \
               -e MLC_CI_SETUP_DEPS 1 -j `nproc` \
               -v ${ADRENOACCL_SDK} /adrenoaccl_sdk \
               -e ADRENOACCL_SDK /adrenoaccl_sdk \
               conda run -n py38 ./ci/adreno/build_clean.sh
           cd -
      - name: Build LLM Models
        shell: bash -l {0}
        run: |
           conda remove -y --name mlc-ci --all
           conda create -y -n mlc-ci -c conda-forge \
               llvmdev=15 cmake>=3.24 git rust numpy \
               decorator psutil typing_extensions scipy \
               attrs git-lfs gcc=10.4 gxx=10.4 python=3.8
           conda activate mlc-ci
           conda env list
           pip install nightly/mlc_llm_adreno_cuda*.whl
           pip install nightly/tvm_adreno_mlc_cuda*.whl
           export LD_LIBRARY_PATH=$CUDA_PATH/lib64/
           export PATH=$CUDA_PATH/bin:$PATH
           python -c "import mlc_llm; print(mlc_llm.__path__)"
           python -c "import tvm; print(tvm.__path__)"
           sh ci/task/build_adreno_models.sh $LLM_MODEL_REPO $LLM_ARTIFACTS
      - name: Publish Artifacts
        shell: bash -l {0}
        run: |
           gh release delete mlc-nightly --cleanup-tag --yes --repo "$RELEASE_REPO" || true
           gh release create mlc-nightly --latest --title mlc-nightly --repo "$RELEASE_REPO" --notes "MLC Nightly builds"
           gh release upload mlc-nightly ../../nightly/*.whl --clobber --repo "$RELEASE_REPO"
           rm -rf ../../nightly/
           gh release delete llm-nightly-artifacts --cleanup-tag --yes --repo "$RELEASE_REPO" || true
           gh release create llm-nightly-artifacts --latest --title llm-nightly-artifacts --repo "$RELEASE_REPO" --notes "Android (Adreno) LLM Nightly artifacts"
           gh release upload llm-nightly-artifacts $LLM_ARTIFACTS/dist/libs/*.so --clobber --repo "$RELEASE_REPO"

  BuildPackageWindows:
    needs: [BuildPackageLinux]
    if: ${{ github.repository == 'gpgpu/mlc-llm' }}
    runs-on: mlc-windows
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ref: ''
      - name: Compile MLC
        shell: powershell
        run: |
           Push-Location
           New-Item -ItemType Directory -Force -Path "./build"
           cd build
           echo $Env:PATH
           Add-Content config.cmake "set(TVM_HOME 3rdparty/tvm)"
           Add-Content config.cmake "set(CMAKE_BUILD_TYPE RelWithDebInfo)"
           Add-Content config.cmake "set(USE_CUDA OFF)"
           Add-Content config.cmake "set(USE_CUTLASS OFF)"
           Add-Content config.cmake "set(USE_CUBLAS OFF)"
           Add-Content config.cmake "set(USE_ROCM OFF)"
           Add-Content config.cmake "set(USE_VULKAN OFF)"
           Add-Content config.cmake "set(USE_METAL OFF)"
           Add-Content config.cmake "set(USE_OPENCL $ENV:OPENCL_SDK_ADRENO_X86)"
           Add-Content config.cmake "set(USE_OPENCL_ENABLE_HOST_PTR ON)"
           Add-Content config.cmake "set(USE_FLASHINFER OFF)"
           Add-Content config.cmake "set(USE_ADRENO_ACCL $ENV:ADRENOACCL_SDK_X86)"
           Add-Content config.cmake "set(USE_ADRENO_ACCL_GRAPH_EXECUTOR $ENV:ADRENOACCL_SDK_X86)"
           cmake .. -G "Visual Studio 17 2022" -A x64
           cmake --build . --config Release --parallel $env:NUMBER_OF_PROCESSORS
           Pop-Location
      - name: Compile TVM
        shell: powershell
        run: |
           Push-Location
           New-Item -ItemType Directory -Force -Path "./3rdparty/tvm/build"
           cd 3rdparty/tvm/build/;
           cp ../cmake/config.cmake .
           Add-Content config.cmake "set(USE_OPENCL $ENV:OPENCL_SDK_ADRENO_X86)"
           Add-Content config.cmake "set(USE_LLVM $ENV:LLVM_CONFIG)"
           Add-Content config.cmake "set(USE_ADRENO_ACCL $ENV:ADRENOACCL_SDK_X86)"
           Add-Content config.cmake "set(USE_ADRENO_ACCL_GRAPH_EXECUTOR $ENV:ADRENOACCL_SDK_X86)"
           cmake .. -G "Visual Studio 17 2022" -A x64
           cmake --build . --config Release --parallel $env:NUMBER_OF_PROCESSORS
           Pop-Location
      - name: Check Build Status
        shell: powershell
        run: |
           $env:PYTHONPATH = "$pwd\3rdparty\tvm\python;python"
           python -c "import mlc_llm; print(mlc_llm.__path__)"
      - name: Build Package and Publish
        shell: powershell
        run: |
           Push-Location
           $Env:WHEEL_EXT_NAME="_adreno_cpu"
           cd python
           python.exe .\setup.py bdist_wheel --plat-name win_amd64
           Pop-Location
           Push-Location
           cd 3rdparty/tvm/python
           python.exe .\setup.py bdist_wheel --plat-name win_amd64
           Pop-Location
           #try { gh release delete mlc-nightly --cleanup-tag --yes --repo $Env:RELEASE_REPO } catch { }
           #gh release create mlc-nightly --latest --title mlc-nightly --repo $Env:RELEASE_REPO --notes "Windows MLC nightly builds"
           foreach ($i in Get-ChildItem -Path python/dist) {gh release upload mlc-nightly .\python\dist\$i --clobber --repo $Env:RELEASE_REPO}
           foreach ($i in Get-ChildItem -Path 3rdparty/tvm/python/dist) {gh release upload mlc-nightly .\3rdparty\tvm\python\dist\$i --clobber --repo $Env:RELEASE_REPO}
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
